create extension if not exists pgcrypto;

create table if not exists public.accounting_companies (id uuid primary key default gen_random_uuid(), external_company_id uuid not null unique, accounting_framework text not null default 'pgc_nirf', tax_regime text, currency_code char(3) not null default 'MZN', fiscal_year_start smallint not null default 1 check(fiscal_year_start between 1 and 12), setup_status text not null default 'setup' check(setup_status in ('setup','ready','review')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.fiscal_periods (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.accounting_companies(id) on delete cascade, period_year integer not null, starts_on date not null, ends_on date not null, status text not null default 'open' check(status in ('open','closed','locked')), unique(company_id,period_year));
create table if not exists public.chart_of_accounts (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.accounting_companies(id) on delete cascade, code text not null, name text not null, parent_id uuid references public.chart_of_accounts(id), account_class smallint, account_type text not null check(account_type in ('asset','liability','equity','revenue','expense','tax','memo')), normal_balance text not null check(normal_balance in ('debit','credit')), system_key text, is_header boolean not null default false, active boolean not null default true, unique(company_id,code));
create table if not exists public.tax_rules (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.accounting_companies(id) on delete cascade, code text not null, name text not null, tax_type text not null, rate numeric(12,6), effective_from date not null, effective_to date, legal_reference text, parameters jsonb not null default '{}'::jsonb, active boolean not null default true, unique(company_id,code,effective_from));
create table if not exists public.accounting_events (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.accounting_companies(id) on delete cascade, source_type text not null, source_id uuid not null, event_version integer not null default 1, occurred_at timestamptz not null, idempotency_key text not null, payload jsonb not null default '{}'::jsonb, status text not null default 'received' check(status in ('received','classified','posted','needs_review','rejected')), created_at timestamptz not null default now(), unique(company_id,idempotency_key));
create table if not exists public.journal_entries (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.accounting_companies(id) on delete cascade, entry_no bigint generated always as identity, entry_date date not null, description text not null, source_event_id uuid references public.accounting_events(id), status text not null default 'posted' check(status in ('draft','posted','reversed')), created_at timestamptz not null default now(), unique(company_id,entry_no));
create table if not exists public.journal_lines (id uuid primary key default gen_random_uuid(), journal_entry_id uuid not null references public.journal_entries(id) on delete cascade, account_id uuid not null references public.chart_of_accounts(id), line_no integer not null, debit numeric(18,2) not null default 0 check(debit>=0), credit numeric(18,2) not null default 0 check(credit>=0), tax_rule_id uuid references public.tax_rules(id), description text, check((debit>0 and credit=0) or (credit>0 and debit=0)), unique(journal_entry_id,line_no));
create index if not exists idx_events_company_status on public.accounting_events(company_id,status);
create index if not exists idx_journal_company_date on public.journal_entries(company_id,entry_date);
create index if not exists idx_journal_lines_entry on public.journal_lines(journal_entry_id);